"""add live chat mode tables

Revision ID: 617bce7dc1f4
Revises: 969f4819b169
Create Date: 2026-04-22 22:42:20.040110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617bce7dc1f4'
down_revision = '969f4819b169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('active_image_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(length=100), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['active_image_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_session_project_id'), ['project_id'], unique=False)

    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(length=50), nullable=False),
    sa.Column('speaker_name', sa.String(length=255), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('message_role', sa.String(length=50), nullable=True),
    sa.Column('state_snapshot_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_session_id'), ['session_id'], unique=False)

    op.create_table('session_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_character_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_character_session_id'), ['session_id'], unique=False)

    op.create_table('session_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('state_json', sa.Text(), nullable=True),
    sa.Column('quality', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('is_selected', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_image_session_id'), ['session_id'], unique=False)

    op.create_table('session_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=False),
    sa.Column('narration_note', sa.Text(), nullable=True),
    sa.Column('visual_prompt_text', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_state_session_id'), ['session_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_state_session_id'))

    op.drop_table('session_state')
    with op.batch_alter_table('session_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_image_session_id'))

    op.drop_table('session_image')
    with op.batch_alter_table('session_character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_character_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_character_character_id'))

    op.drop_table('session_character')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_session_id'))

    op.drop_table('chat_message')
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_session_project_id'))

    op.drop_table('chat_session')
    # ### end Alembic commands ###
