"""player select

Revision ID: 74ad095217cf
Revises: c1c314626be5
Create Date: 2026-04-19 23:13:12.469820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ad095217cf'
down_revision = 'c1c314626be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scene_character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_character_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scene_character_scene_id'), ['scene_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scene_character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_character_scene_id'))
        batch_op.drop_index(batch_op.f('ix_scene_character_character_id'))

    op.drop_table('scene_character')
    # ### end Alembic commands ###
