"""add story memory and missing tables

Revision ID: 8120f6d07f47
Revises: 2e14e3456777
Create Date: 2026-04-19 17:42:29.900391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8120f6d07f47'
down_revision = '2e14e3456777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('memory_key', sa.String(length=100), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_memory')
    # ### end Alembic commands ###
