"""add story memory and missing tables

Revision ID: c1c314626be5
Revises: 8120f6d07f47
Create Date: 2026-04-19 18:12:07.859396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c314626be5'
down_revision = '8120f6d07f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text_ai_model', sa.String(length=100), nullable=False),
    sa.Column('image_ai_model', sa.String(length=100), nullable=False),
    sa.Column('default_quality', sa.String(length=20), nullable=False),
    sa.Column('default_size', sa.String(length=20), nullable=False),
    sa.Column('autosave_interval', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_setting_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_setting_user_id'))

    op.drop_table('user_setting')
    # ### end Alembic commands ###
