"""drop obsolete novel tables

Revision ID: e7cca3af1c56
Revises: 617bce7dc1f4
Create Date: 2026-04-25 00:54:33.021708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7cca3af1c56'
down_revision = '617bce7dc1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scene_image')
    op.drop_table('scene_choice')
    op.drop_table('story_memory')
    with op.batch_alter_table('scene_character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_character_character_id'))
        batch_op.drop_index(batch_op.f('ix_scene_character_scene_id'))

    op.drop_table('scene_character')
    with op.batch_alter_table('session_character', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_character_character_id'))
        batch_op.drop_index(batch_op.f('ix_session_character_session_id'))

    op.drop_table('session_character')
    op.drop_table('scene')
    op.drop_table('scene_version')
    op.drop_table('chapter')
    op.drop_table('generation_job')
    op.drop_table('export_job')
    op.drop_table('story_outline')
    op.drop_table('generated_candidate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_candidate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('target_id', sa.INTEGER(), nullable=False),
    sa.Column('candidate_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('content_text', sa.TEXT(), nullable=True),
    sa.Column('content_json', sa.TEXT(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('tags_json', sa.TEXT(), nullable=True),
    sa.Column('is_selected', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene_version',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scene_id', sa.INTEGER(), nullable=False),
    sa.Column('version_no', sa.INTEGER(), nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('generated_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('narration_text', sa.TEXT(), nullable=True),
    sa.Column('dialogue_json', sa.TEXT(), nullable=True),
    sa.Column('choice_json', sa.TEXT(), nullable=True),
    sa.Column('scene_state_json', sa.TEXT(), nullable=True),
    sa.Column('image_prompt_text', sa.TEXT(), nullable=True),
    sa.Column('note_text', sa.TEXT(), nullable=True),
    sa.Column('is_adopted', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_character',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('character_id', sa.INTEGER(), nullable=False),
    sa.Column('role_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_character_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_character_character_id'), ['character_id'], unique=False)

    op.create_table('scene_character',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scene_id', sa.INTEGER(), nullable=False),
    sa.Column('character_id', sa.INTEGER(), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scene_character', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_character_scene_id'), ['scene_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scene_character_character_id'), ['character_id'], unique=False)

    op.create_table('scene_image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scene_id', sa.INTEGER(), nullable=False),
    sa.Column('scene_version_id', sa.INTEGER(), nullable=True),
    sa.Column('asset_id', sa.INTEGER(), nullable=False),
    sa.Column('image_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('generation_job_id', sa.INTEGER(), nullable=True),
    sa.Column('prompt_text', sa.TEXT(), nullable=True),
    sa.Column('state_json', sa.TEXT(), nullable=True),
    sa.Column('quality', sa.VARCHAR(length=50), nullable=False),
    sa.Column('size', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_selected', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_job.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.ForeignKeyConstraint(['scene_version_id'], ['scene_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_outline',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('premise', sa.TEXT(), nullable=True),
    sa.Column('protagonist_position', sa.TEXT(), nullable=True),
    sa.Column('main_goal', sa.TEXT(), nullable=True),
    sa.Column('branching_policy', sa.TEXT(), nullable=True),
    sa.Column('ending_policy', sa.TEXT(), nullable=True),
    sa.Column('outline_text', sa.TEXT(), nullable=True),
    sa.Column('outline_json', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('protagonist_name', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('export_job',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('export_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('asset_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('options_json', sa.TEXT(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene_choice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scene_id', sa.INTEGER(), nullable=False),
    sa.Column('choice_text', sa.TEXT(), nullable=False),
    sa.Column('next_scene_id', sa.INTEGER(), nullable=True),
    sa.Column('condition_json', sa.TEXT(), nullable=True),
    sa.Column('result_summary', sa.TEXT(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['next_scene_id'], ['scene.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_job',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('target_id', sa.INTEGER(), nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('request_json', sa.TEXT(), nullable=True),
    sa.Column('response_json', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), nullable=False),
    sa.Column('parent_scene_id', sa.INTEGER(), nullable=True),
    sa.Column('scene_key', sa.VARCHAR(length=255), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('narration_text', sa.TEXT(), nullable=True),
    sa.Column('dialogue_json', sa.TEXT(), nullable=True),
    sa.Column('scene_state_json', sa.TEXT(), nullable=True),
    sa.Column('image_prompt_text', sa.TEXT(), nullable=True),
    sa.Column('active_version_id', sa.INTEGER(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.Column('is_fixed', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['active_version_id'], ['scene_version.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['parent_scene_id'], ['scene.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('chapter_no', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('objective', sa.TEXT(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_memory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), nullable=True),
    sa.Column('scene_id', sa.INTEGER(), nullable=True),
    sa.Column('memory_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('memory_key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('content_text', sa.TEXT(), nullable=False),
    sa.Column('detail_json', sa.TEXT(), nullable=True),
    sa.Column('importance', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
